### ISSUE TITLE
Todo/References

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/LibraryWine#1]
Tag this issue to add references and todo to the LibraryWine project.

### Checks
- [x] Method for validating winepath
- [ ] Check arch compatibility

### Wineprefix management
- [x] Processes management (list, kill)
- [x] Method for commands execution
- [x] Utilities (winecfg, regedit, debug, cmd, taskmanager, controlpanel, uninstaller)
- [x] Run .exe/.msi/.bat
- [x] wineboot handling (kill, restart, shutdown, update)
- [x] Add (or edit) DLL Overrides
- [x] List DLL Overrides from register
- [x] Manage register keys (add, edit, delete)
- [x] Set Windows version
- [x] Set virtual desktop
- [x] Toggle window manager decoration
- [x] Toggle window manager control
- [x] Toggle automatic fullscreen mouse capture
- [x] List/get key values from register
- [x] Toggle window decorations
- [x] Toggle window control
- [x] Support for different data types in register
- [x] Change DPI
- [x] Windows version per application `HKEY_CURRENT_USER\Software\Wine\AppDefaults`
- [ ] Drives management (add, update, delete)
- [ ] Support for runas on command execution

**Comment by ryi3r** [comment]
will this project continue to receive updates?

**Comment by mirkobrombin** [comment]
Might be possible, but we are currently focued on Bottles (py) and Bottles Next (rust). Any contribution is welcome.
